test/data/err_131.py:6:1 [FURB131]: Replace `del x[:]` with `x.clear()`
